import Link from 'next/link'
import Image from 'next/image'
import {site,skills,projects,experience,education,courses} from '../data/site'
import SectionHeading from '../components/SectionHeading'
import ProjectCard from '../components/ProjectCard'

export default function Home(){return <main>
<section className="hero wrap"><div className="hero-copy"><p className="eyebrow">Full Stack Developer · Product Designer</p><h1>Jonathan<br/><i>Daniel</i></h1><p className="hero-lead">I build modern, responsive and user-centered digital experiences — from intuitive interfaces to full-stack applications.</p><div className="actions"><Link className="button dark" href="/projects">View projects <span>↗</span></Link><a className="button outline" href={`mailto:${site.email}`}>Contact me</a></div><div className="contact-strip"><span>{site.location}</span><a href={`tel:${site.phone}`}>{site.phone}</a><a href={`mailto:${site.email}`}>{site.email}</a></div></div><div className="portrait"><Image src="/jonathan-daniel.jpg" alt="Jonathan Daniel" fill priority sizes="(max-width: 850px) 100vw, 45vw"/></div></section>
<section className="projects-preview"><div className="wrap"><SectionHeading eyebrow="01 — Selected work" title="Things I’ve built" intro="A growing collection of products, interfaces and applications. Project screenshots are intentionally given room to breathe."/><div className="project-grid">{projects.map(p=><ProjectCard key={p.slug} project={p}/>)}</div><div className="center"><Link className="button dark" href="/projects">View all projects <span>↗</span></Link></div></div></section>
<section id="about" className="wrap split"><div><SectionHeading eyebrow="02 — About" title="Design with purpose. Build with intent."/></div><div className="prose"><p>I’m a Full Stack Software Developer and Product Designer based in Abuja, Nigeria. My background combines computer science with focused learning in frontend development, UI/UX, full-stack engineering and AI engineering.</p><p>I enjoy solving complex problems, designing intuitive interfaces and using modern technologies to turn ideas into useful digital products.</p><a className="text-link" href="/resume/Jonathan-Daniel-Resume.docx">Download CV <span>↓</span></a></div></section>
<section id="skills" className="tinted"><div className="wrap"><SectionHeading eyebrow="03 — Capabilities" title="A practical toolkit."/><div className="skill-grid">{skills.map((s,i)=><div className="skill" key={s.title}><span className="skill-no">0{i+1}</span><h3>{s.title}</h3><div className="tags">{s.items.map(x=><span key={x}>{x}</span>)}</div></div>)}</div></div></section>
<section id="experience" className="wrap"><SectionHeading eyebrow="04 — Experience" title="Professional journey." intro="Experience across website design and product design, supported by technical training."/><div className="timeline">{experience.map((e,i)=><div className="timeline-row" key={e.role}><div className="timeline-date">{e.date}</div><div><p className="eyebrow">0{i+1}</p><h3>{e.role}</h3><p className="company">{e.company}</p><p className="muted">{e.description}</p></div></div>)}</div></section>
<section id="education" className="tinted"><div className="wrap"><SectionHeading eyebrow="05 — Education & learning" title="Always learning."/><div className="education-grid"><div className="education-main"><p className="eyebrow">Education</p><h3>{education.degree}</h3><p>{education.school}</p><span>{education.period}</span></div><div className="course-grid">{courses.map(c=><div className="course" key={c.title}><h3>{c.title}</h3><p>{c.provider} · {c.period}</p><span>{c.detail}</span></div>)}</div></div></div></section>
<section id="contact" className="contact-section"><div className="wrap contact-grid"><div><p className="eyebrow">06 — Contact</p><h2>Have a project<br/><i>in mind?</i></h2><p className="section-intro">I’m open to new opportunities and exciting projects. Let’s build something considered and useful.</p></div><div className="contact-cards"><a href={`mailto:${site.email}`}><span>Email</span><strong>{site.email}</strong></a><a href={`tel:${site.phone}`}><span>Phone</span><strong>{site.phone}</strong></a><a href={site.linkedin} target="_blank"><span>LinkedIn</span><strong>jonathandaniels14ab ↗</strong></a><Link href="/admin"><span>Portfolio Admin</span><strong>Manage projects ↗</strong></Link></div></div></section>
</main>}
